version: '3.8'

services:
  mtproxy-manager:
    build: .
    container_name: mtproxy-manager
    ports:
      - "8080-8180:8080-8180"  # Proxy ports
      - "8080:8080"            # Web interface
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./backups:/app/backups
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    restart: unless-stopped
    networks:
      - mtproxy-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "python", "mtproxy_manager.py", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mtproxy-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
